/**
 * ⚠️ AUTO-GENERATED — Do not edit manually!
 * 
 * Generated by @tanstack/vite-plugin at build time.
 * This is a minimal stub for development; the real file is generated during `npm run build`.
 */

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const _routeTree: any = {} as any

export { _routeTree as routeTree }
