/**
 * ⚠️ AUTO-GENERATED — Do not edit manually!
 * 
 * This file is auto-generated by @tanstack/vite-plugin during development/build.
 * If this file is missing or causing errors, run:
 *   npx vite build    (generates via plugin)
 *   npm run dev        (generates on startup)
 * 
 * Last generated: 2026-06-08
 */

// Minimal type stub for TypeScript — real types come from @tanstack/vite-plugin
export const routeTree: Record<string, unknown> = {}

// Re-export for backward compatibility
export type { FileRoutesByPath } from '@tanstack/react-router'
declare module './routeTree.gen' {
  export { routeTree }
  import { routeTree } from './routeTree.gen.actual'
  export type { FileRoutesByPath }
}
