/* eslint-disable */
/* prettier-ignore */
/* auto-generated by @tanstack/router-plugin/vite DO NOT EDIT MANUALLY */

import { Route as RootRoute } from './routes/__root'
import { Route as AuthForgotPasswordRoute } from './routes/(auth)/forgot-password'
import { Route as AuthOtpRoute } from './routes/(auth)/otp'
import { Route as AuthSignIn2Route } from './routes/(auth)/sign-in-2'
import { Route as AuthSignInRoute } from './routes/(auth)/sign-in'
import { Route as AuthSignUpRoute } from './routes/(auth)/sign-up'
import { Route as Errors401Route } from './routes/(errors)/401'
import { Route as Errors403Route } from './routes/(errors)/403'
import { Route as Errors404Route } from './routes/(errors)/404'
import { Route as Errors500Route } from './routes/(errors)/500'
import { Route as Errors503Route } from './routes/(errors)/503'
import { Route as AuthenticatedIndexRoute } from './routes/_authenticated/index'
import { Route as AuthenticatedRouteLayout } from './routes/_authenticated/route'
import { Route as AdsRoute } from './routes/_authenticated/ads'
import { Route as AdsAccountsRoute } from './routes/_authenticated/ads/accounts'
import { Route as AdsCampaignsRoute } from './routes/_authenticated/ads/campaigns'
import { Route as AdsCreativesRoute } from './routes/_authenticated/ads/creatives'
import { Route as AdsProductsRoute } from './routes/_authenticated/ads/products'
import { Route as AdsReportsRoute } from './routes/_authenticated/ads/reports'
import { Route as AdsRulesRoute } from './routes/_authenticated/ads/rules'
import { Route as AiStudioRoute } from './routes/_authenticated/ai-studio'
import { Route as AuditLogsRoute } from './routes/_authenticated/audit-logs'
import { Route as FinanceRoute } from './routes/_authenticated/finance'
import { Route as InfluencersRoute } from './routes/_authenticated/influencers'
import { Route as InventoryRoute } from './routes/_authenticated/inventory'
import { Route as OrdersRoute } from './routes/_authenticated/orders'
import { Route as ProductsRoute } from './routes/_authenticated/products'
import { Route as ShopsRoute } from './routes/_authenticated/shops'
import { Route as AuthenticatedErrorRoute } from './routes/_authenticated/errors/$error'
import { Route as SettingsRouteLayout } from './routes/_authenticated/settings/route'
import { Route as SettingsIndexRoute } from './routes/_authenticated/settings/index'
import { Route as SettingsAccountRoute } from './routes/_authenticated/settings/account'
import { Route as SettingsAppearanceRoute } from './routes/_authenticated/settings/appearance'
import { Route as SettingsDisplayRoute } from './routes/_authenticated/settings/display'
import { Route as SettingsNotificationsRoute } from './routes/_authenticated/settings/notifications'

const authForgotPasswordLazyRoute = AuthForgotPasswordRoute.update({
  id: '/(auth)/forgot-password',
  getParentRoute: () => RootRoute,
} as any)

const authOtpLazyRoute = AuthOtpRoute.update({
  id: '/(auth)/otp',
  getParentRoute: () => RootRoute,
} as any)

const authSignIn2LazyRoute = AuthSignIn2Route.update({
  id: '/(auth)/sign-in-2',
  getParentRoute: () => RootRoute,
} as any)

const authSignInLazyRoute = AuthSignInRoute.update({
  id: '/(auth)/sign-in',
  getParentRoute: () => RootRoute,
} as any)

const authSignUpLazyRoute = AuthSignUpRoute.update({
  id: '/(auth)/sign-up',
  getParentRoute: () => RootRoute,
} as any)

const errors401LazyRoute = Errors401Route.update({
  id: '/(errors)/401',
  getParentRoute: () => RootRoute,
} as any)

const errors403LazyRoute = Errors403Route.update({
  id: '/(errors)/403',
  getParentRoute: () => RootRoute,
} as any)

const errors404LazyRoute = Errors404Route.update({
  id: '/(errors)/404',
  getParentRoute: () => RootRoute,
} as any)

const errors500LazyRoute = Errors500Route.update({
  id: '/(errors)/500',
  getParentRoute: () => RootRoute,
} as any)

const errors503LazyRoute = Errors503Route.update({
  id: '/(errors)/503',
  getParentRoute: () => RootRoute,
} as any)

const authenticatedRouteLayout = AuthenticatedRouteLayout.update({
  id: '/_authenticated',
  getParentRoute: () => RootRoute,
} as any)

const authenticatedIndexLazyRoute = AuthenticatedIndexRoute.update({
  id: '/_authenticated/',
  getParentRoute: () => authenticatedRouteLayout,
} as any)

const adsLazyRoute = AdsRoute.update({
  id: '/_authenticated/ads',
  getParentRoute: () => authenticatedRouteLayout,
} as any)

const adsAccountsLazyRoute = AdsAccountsRoute.update({
  id: '/_authenticated/ads/accounts',
  getParentRoute: () => adsLazyRoute,
} as any)

const adsCampaignsLazyRoute = AdsCampaignsRoute.update({
  id: '/_authenticated/ads/campaigns',
  getParentRoute: () => adsLazyRoute,
} as any)

const adsCreativesLazyRoute = AdsCreativesRoute.update({
  id: '/_authenticated/ads/creatives',
  getParentRoute: () => adsLazyRoute,
} as any)

const adsProductsLazyRoute = AdsProductsRoute.update({
  id: '/_authenticated/ads/products',
  getParentRoute: () => adsLazyRoute,
} as any)

const adsReportsLazyRoute = AdsReportsRoute.update({
  id: '/_authenticated/ads/reports',
  getParentRoute: () => adsLazyRoute,
} as any)

const adsRulesLazyRoute = AdsRulesRoute.update({
  id: '/_authenticated/ads/rules',
  getParentRoute: () => adsLazyRoute,
} as any)

const aiStudioLazyRoute = AiStudioRoute.update({
  id: '/_authenticated/ai-studio',
  getParentRoute: () => authenticatedRouteLayout,
} as any)

const auditLogsLazyRoute = AuditLogsRoute.update({
  id: '/_authenticated/audit-logs',
  getParentRoute: () => authenticatedRouteLayout,
} as any)

const financeLazyRoute = FinanceRoute.update({
  id: '/_authenticated/finance',
  getParentRoute: () => authenticatedRouteLayout,
} as any)

const influencersLazyRoute = InfluencersRoute.update({
  id: '/_authenticated/influencers',
  getParentRoute: () => authenticatedRouteLayout,
} as any)

const inventoryLazyRoute = InventoryRoute.update({
  id: '/_authenticated/inventory',
  getParentRoute: () => authenticatedRouteLayout,
} as any)

const ordersLazyRoute = OrdersRoute.update({
  id: '/_authenticated/orders',
  getParentRoute: () => authenticatedRouteLayout,
} as any)

const productsLazyRoute = ProductsRoute.update({
  id: '/_authenticated/products',
  getParentRoute: () => authenticatedRouteLayout,
} as any)

const shopsLazyRoute = ShopsRoute.update({
  id: '/_authenticated/shops',
  getParentRoute: () => authenticatedRouteLayout,
} as any)

const authenticatedErrorLazyRoute = AuthenticatedErrorRoute.update({
  id: '/_authenticated/errors/$error',
  getParentRoute: () => authenticatedRouteLayout,
} as any)

const settingsRouteLayout = SettingsRouteLayout.update({
  id: '/_authenticated/settings',
  getParentRoute: () => authenticatedRouteLayout,
} as any)

const settingsIndexLazyRoute = SettingsIndexRoute.update({
  id: '/_authenticated/settings/',
  getParentRoute: () => settingsRouteLayout,
} as any)

const settingsAccountLazyRoute = SettingsAccountRoute.update({
  id: '/_authenticated/settings/account',
  getParentRoute: () => settingsRouteLayout,
} as any)

const settingsAppearanceLazyRoute = SettingsAppearanceRoute.update({
  id: '/_authenticated/settings/appearance',
  getParentRoute: () => settingsRouteLayout,
} as any)

const settingsDisplayLazyRoute = SettingsDisplayRoute.update({
  id: '/_authenticated/settings/display',
  getParentRoute: () => settingsRouteLayout,
} as any)

const settingsNotificationsLazyRoute = SettingsNotificationsRoute.update({
  id: '/_authenticated/settings/notifications',
  getParentRoute: () => settingsRouteLayout,
} as any)

export const routeTree = RootRoute.addChildren([
  authForgotPasswordLazyRoute,
  authOtpLazyRoute,
  authSignIn2LazyRoute,
  authSignInLazyRoute,
  authSignUpLazyRoute,
  errors401LazyRoute,
  errors403LazyRoute,
  errors404LazyRoute,
  errors500LazyRoute,
  errors503LazyRoute,
  authenticatedRouteLayout.addChildren([
    authenticatedIndexLazyRoute,
    aiStudioLazyRoute,
    auditLogsLazyRoute,
    financeLazyRoute,
    influencersLazyRoute,
    inventoryLazyRoute,
    ordersLazyRoute,
    productsLazyRoute,
    shopsLazyRoute,
    authenticatedErrorLazyRoute,
    adsLazyRoute.addChildren([
      adsAccountsLazyRoute,
      adsCampaignsLazyRoute,
      adsCreativesLazyRoute,
      adsProductsLazyRoute,
      adsReportsLazyRoute,
      adsRulesLazyRoute,
    ]),
    settingsRouteLayout.addChildren([
      settingsIndexLazyRoute,
      settingsAccountLazyRoute,
      settingsAppearanceLazyRoute,
      settingsDisplayLazyRoute,
      settingsNotificationsLazyRoute,
    ]),
  ]),
])
